package ca.bcit.winter2021.comp2522.midterm.problem2;

public enum FixtureName {
    SOUNDWAVE,
    BLUESTREAK,
    HUBCAP,
    PREDAKING,
    REWIND,
    GRIMLOCK,
    RAZORCLAW,
    FREEWAY,
    BARRAGE,
    COMPUTRON,
    OPTIMUSPRIME,
    MEGATRON,
    DIVEBOMB,
    CUTTHROAT,
    HEADSTRONG,
    KICKBACK,
    SKYDIVE,
    BLASTER,
    SANDSTORM,
    REPUGNUS,
    GEARS,
    HARDHEAD,
    DOUBLECROSS,
    CLIFFJUMPER,
    SCAVENGER,
    TEST;
}
